- name: Run Container on Docker
  hosts: target
  user: jenkins
  become: true
  become_method: sudo
  gather_facts: false

  vars:
    create_containers: 1
    default_container_name: jenkins
    default_container_image: jenkins

  tasks:
    - name: Install Python
      yum:
        name:
          - python
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create container
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        state: started
        ports: "8080:8080, 50000:50000"
        volume: "jenkins_home:/var/jenkins_home"
